# Generated by Django 4.2.8 on 2023-12-26 04:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(error_messages='Emalini to`g`ri kiriting', max_length=254)),
                ('message', models.TextField()),
            ],
        )
    ]
