# Generated by Django 4.2.8 on 2024-01-06 17:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contactform_rename_newsa_newa_alter_newa_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newa',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
