# Generated by Django 4.2.9 on 2024-01-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newa',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newa',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newa',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newa',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newa',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newa',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
